#+TITLE: ZSH Scripts Providing a ROFI Interface



This [[https://orgmode.org/][orgmode]] file is both the documentation and the original source code for the scripts in this folder. They use the =etabli.py= script in combination with some basic =zsh= scripting to interact with the [[https://github.com/davatorium/rofi][rofi]] launcher, and use it to provide a convenient interface to deal with workspaces and levels.

Similar results could be achieved using =jq= to for instance parse the output of =swaymsg -t get_workspaces= (in fact, this is how these scripts started), but I preferred to get rid of the dependence on =jq= and instead have =etabli.py= handle such interaction, the aim being to allow abritrarily complex processing down the line.

* Building the ZSH Scripts
** Renaming
We need to grab the name of the current workspace (I use the method given [[https://gist.github.com/Sprit3Dan/bb730c9405d4632cc90a1d36b5400207][here]], the name to give (using rofi in =-dmenu= mode), and then the right message via =swaymsg=.

We use =-i= to get rid of case sensitivity. If you disagree, simply remove that option.

#+BEGIN_SRC sh :tangle ./rofi-workspace-rename :results output silent
#!/usr/bin/sh

OLD_NAME=$(python3 ~/etabli/etabli.py current_workspace)
NEW_NAME=$(rofi -dmenu -i -p "Enter new name (old was $OLD_NAME)")
if [[ $NEW_NAME ]]; then
    swaymsg rename workspace $OLD_NAME to $NEW_NAME
else
    echo "not doing anything"
fi
#+END_SRC
** Switching
We grab the name of all the workspaces by parsing the output of =swaymsg -t get_workspaces= using =jq=, and then use =rofi= to select one.

#+BEGIN_SRC sh :tangle ./rofi-workspace-switch :results output silent
#!/usr/bin/zsh

WORKSPACES=$(python3 ~/etabli/etabli.py get_workspaces)
echo $WORKSPACES
SELECTED_WORKSPACE=$(echo $WORKSPACES | rofi -dmenu -i -p "Go to workspace" -theme-str "listview {lines: 15; columns: 2;}")
if [[ $SELECTED_WORKSPACE ]]; then
    swaymsg workspace "$SELECTED_WORKSPACE"
else
    echo "not doing anything"
fi
#+END_SRC
** Sending container
Basically identical to the [[*Switching][previous script]], but this one sends the
focused window there.

After sending the container, we "follow" it by also switching the
workspace.
#+BEGIN_SRC sh :tangle ./rofi-workspace-send :results output silent
#!/usr/bin/zsh

WORKSPACES=$(python3 ~/etabli/etabli.py get_workspaces)
echo $WORKSPACES
SELECTED_WORKSPACE=$(echo $WORKSPACES | rofi -dmenu -i -p "Send window to workspace")
if [[ $SELECTED_WORKSPACE ]]; then
    swaymsg move container to workspace "$SELECTED_WORKSPACE"
    swaymsg workspace "$SELECTED_WORKSPACE"
else
    echo "not doing anything"
fi
#+END_SRC

* Usage
To use these scripts, simply add something like the following snippet to your =sway= configuration, where =path/to/rofi_folder/= needs to be replaced by the actual path to this folder.

#+BEGIN_SRC
bindsym $mod+n exec zsh path/to/rofi_folder/rofi-workspace-rename
bindsym $mod+b exec zsh path/to/rofi_folder/rofi-workspace-switch
bindsym $mod+Shift+b exec zsh path/to/rofi_folder/rofi-workspace-send
#+END_SRC

