#!/usr/bin/zsh

WORKSPACES=$(etabli --list_workspaces)
echo $WORKSPACES
SELECTED_WORKSPACE=$(echo $WORKSPACES | rofi -dmenu -i -monitor -1 -config ~/.config/rofi/rofi.rasi -p  "Go to workspace" | awk -F " " '{print $NF}')
if [[ $SELECTED_WORKSPACE ]]; then
    swaymsg workspace "$SELECTED_WORKSPACE"
else
    echo "not doing anything"

fi
