#!/usr/bin/zsh

OLD_NAME=$(etabli --current_workspace)
LEVEL=$(etabli current_level)
NEW_NAME=$(etabli prepare | rofi -dmenu -i -monitor -1 -config ~/.config/rofi/rofi.rasi -p  "Enter new name (old was \`$OLD_NAME\`)" -filter $LEVEL/ -l 0 | awk -F " " '{print $NF}')


if [[ $NEW_NAME ]]; then
    swaymsg rename workspace $OLD_NAME to $NEW_NAME
else
    echo "not doing anything"
fi
