#!/usr/bin/zsh

CURRENT_DIRECTORY=$(etabli get_level_variable directory)
if [[ $CURRENT_DIRECTORY == "" ]]; then
    EXPLAIN="New level directory"
else
    EXPLAIN="New level directory (old was \`$CURRENT_DIRECTORY\`)"
fi

NEW_DIRECTORY=$(find ~/ -type d -not -path "*/.*" -not -path "*miniforge*" | rofi -dmenu -i)
echo $NEW_DIRECTORY
if [[ $NEW_DIRECTORY ]]; then
    etabli set_level_variable directory "$NEW_DIRECTORY"
else
    echo "doing nothing"
fi
