#!/usr/bin/zsh

WORKSPACES=$(python3 ~/etabli/etabli.py get_workspaces)
echo $WORKSPACES
SELECTED_WORKSPACE=$(echo $WORKSPACES | rofi -dmenu -i -p "Go to workspace")
if [[ $SELECTED_WORKSPACE ]]; then
    swaymsg workspace "$SELECTED_WORKSPACE"
else
    echo "not doing anything"
fi
