#!/usr/bin/zsh

if (($1==1)); then
   WORKSPACE=$(python3 ~/etabli/etabli.py name_next_workspace_in_level)
else
   WORKSPACE=$(python3 ~/etabli/etabli.py name_previous_workspace_in_level)
fi
echo "$WORKSPACE"
swaymsg move container to workspace "$WORKSPACE"
swaymsg workspace "$WORKSPACE"
