[theme]

[theme.sp]
FOCUSED = "<span color='#C00000'>{}</span>"
FOCUSED_LEVEL = "<span color='#865509'>{}</span>"
VISIBLE_LEVEL_OTHER_OUTPUT = "<span color='#865509'>{}</span>"
NOT_VISIBLE_CURRENT_OUTPUT = "<span color='#707070'>{}</span>"
NOT_VISIBLE_OTHER_OUTPUT =   "<span color='#999999'>{}</span>"

[theme.ontop]
VISIBLE_LEVEL_OTHER_OUTPUT =  "<span underline='single' underline_color='#C00000' color='#707070'>{}</span>"
NOT_VISIBLE_CURRENT_OUTPUT = "<span color='#865509'>{}</span>"
NOT_VISIBLE_OTHER_OUTPUT = "<span color='#865509'>{}</span>"

[theme.lvl]
FOCUSED_LEVEL = "<span style='italic' color='#C00000'>{}</span>"
VISIBLE_LEVEL_OTHER_OUTPUT =  "<span style='italic' color='#bd7504'>{}</span>"
NOT_VISIBLE_CURRENT_OUTPUT = "<span style='italic' color='#bd7504'>{}</span>"
NOT_VISIBLE_OTHER_OUTPUT =  "<span style='italic' color='#865509'>{}</span>"

[theme.sbl]

[theme.sbl.open]
FOCUSED_LEVEL =              "<span color='#C00000'> (</span>"
VISIBLE_LEVEL_OTHER_OUTPUT = "<span color='#bd7504'> (</span>"
NOT_VISIBLE_CURRENT_OUTPUT = "<span color='#707070'> (</span>"
NOT_VISIBLE_OTHER_OUTPUT =   "<span color='#707070'> (</span>"

[theme.sbl.close]
FOCUSED_LEVEL =              "<span color='#C00000'>) </span>"
VISIBLE_LEVEL_OTHER_OUTPUT = "<span color='#bd7504'>) </span>"
NOT_VISIBLE_CURRENT_OUTPUT = "<span color='#707070'>) </span>"
NOT_VISIBLE_OTHER_OUTPUT =   "<span color='#707070'>) </span>"


[theme.brd]
dlm_color = "#881144"
key_color = "#707070"
txt_color = "#252525"
dlm = " | "
